#!/usr/bin/env python3
"""Build Resources/places.tsv from GeoNames (https://www.geonames.org, CC BY 4.0).

    Tools/make_places.py <dir with cities15000.txt, countryInfo.txt, admin1CodesASCII.txt>

One line per city with 15,000+ people: name, lat, lon, region, country, population,
its Chinese/Japanese/Korean names so they can be searched, and its IANA time zone
(the offset at any instant then comes from the system's own tz database). The app reads this
file offline; nothing is ever looked up on the network.
"""
import sys, os, re
src = sys.argv[1]
cjk = re.compile(r'[぀-ヿ㐀-鿿가-힯]')
countries = {}
for line in open(os.path.join(src, "countryInfo.txt"), encoding="utf-8"):
    if line.startswith("#"): continue
    f = line.rstrip("\n").split("\t")
    if len(f) > 4: countries[f[0]] = f[4]
admin1 = {}
for line in open(os.path.join(src, "admin1CodesASCII.txt"), encoding="utf-8"):
    f = line.rstrip("\n").split("\t")
    if len(f) > 1: admin1[f[0]] = f[1]
out = []
for line in open(os.path.join(src, "cities15000.txt"), encoding="utf-8"):
    f = line.rstrip("\n").split("\t")
    name, ascii_, alts, lat, lon, cc, a1, pop, tz = f[1], f[2], f[3], f[4], f[5], f[8], f[10], f[14], f[17]
    local = []
    for a in alts.split(","):
        if cjk.search(a) and a not in local: local.append(a)
    out.append("\t".join([
        name, ascii_ if ascii_ != name else "", "%.4f" % float(lat), "%.4f" % float(lon),
        admin1.get(cc + "." + a1, ""), countries.get(cc, cc), pop, ",".join(local[:4]), tz]))
out.sort(key=lambda l: -int(l.split("\t")[6] or 0))
dst = os.path.join(os.path.dirname(__file__), "..", "Resources", "places.tsv")
with open(dst, "w", encoding="utf-8") as fh:
    fh.write("# GeoNames cities15000 (https://www.geonames.org), CC BY 4.0. Generated by Tools/make_places.py\n")
    fh.write("\n".join(out) + "\n")
print(len(out), "places ->", os.path.relpath(dst))
